name: codecov

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.18'
    - name: Run coverage
      run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic
    - name: Upload to codecov
      uses: codecov/codecov-action@v3.1.1

